// auto-generated by scripts/generate-font.ts - do not edit manually
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai
//
// next/font/google downloads this font at build time, self-hosts it under
// /_next/static/media/, and generates @font-face with font-display: swap plus
// fallback metric overrides (ascent-override / descent-override / size-adjust)
// to prevent CLS - same technique as fontaine / @nuxt/fonts.

import { Poppins } from 'next/font/google'

const font = Poppins({
  subsets: ['latin'],
  variable: '--font-base',
  weight: ['400', '500', '600', '700'],
})
export default font
