// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai

import { describe, expect, it } from 'bun:test'
import { buildFontContent, WEIGHTS } from '../../scripts/generate-font'
import type { FontName } from '@/types/config'

// ── WEIGHTS ───────────────────────────────────────────────────────────────────

describe('WEIGHTS', () => {
  it('Roboto has expected weight array', () => {
    expect(WEIGHTS.Roboto).toEqual(['300', '400', '500', '700'])
  })

  it('Poppins has expected weight array', () => {
    expect(WEIGHTS.Poppins).toEqual(['300', '400', '500', '600', '700'])
  })

  it('Lato has expected weight array', () => {
    expect(WEIGHTS.Lato).toEqual(['300', '400', '700'])
  })

  it('Barlow has expected weight array', () => {
    expect(WEIGHTS.Barlow).toEqual(['300', '400', '500', '600', '700'])
  })

  it('IBM_Plex_Mono has expected weight array', () => {
    expect(WEIGHTS.IBM_Plex_Mono).toEqual(['300', '400', '500', '700'])
  })

  it('single-weight display fonts have weight 400', () => {
    expect(WEIGHTS.Bebas_Neue).toEqual(['400'])
    expect(WEIGHTS.Anton).toEqual(['400'])
    expect(WEIGHTS.DM_Serif_Display).toEqual(['400'])
  })

  it('variable fonts are not in WEIGHTS', () => {
    // These are variable fonts — next/font handles weight automatically
    const variableFonts: FontName[] = [
      'Inter',
      'Geist',
      'Montserrat',
      'Raleway',
      'Nunito',
      'Space_Grotesk',
      'DM_Sans',
      'Outfit',
      'Playfair_Display',
      'Manrope',
      'Plus_Jakarta_Sans',
    ]
    for (const font of variableFonts) {
      expect(WEIGHTS[font]).toBeUndefined()
    }
  })

  it('every weight value is a string of digits', () => {
    for (const weights of Object.values(WEIGHTS)) {
      if (!weights) continue
      for (const w of weights) {
        expect(w).toMatch(/^\d+$/)
      }
    }
  })
})

// ── buildFontContent ──────────────────────────────────────────────────────────

describe('buildFontContent', () => {
  it('imports the correct font from next/font/google', () => {
    const content = buildFontContent('Inter')
    expect(content).toContain("import { Inter } from 'next/font/google'")
  })

  it('uses the correct font constructor', () => {
    const content = buildFontContent('Poppins')
    expect(content).toContain('Poppins({')
  })

  it('always sets subsets latin and variable --font-base', () => {
    for (const name of ['Inter', 'Roboto', 'Playfair_Display'] as FontName[]) {
      const content = buildFontContent(name)
      expect(content).toContain("subsets: ['latin']")
      expect(content).toContain("variable: '--font-base'")
    }
  })

  it('includes weight array for static multi-weight fonts', () => {
    const content = buildFontContent('Roboto')
    expect(content).toContain('weight:')
    expect(content).toContain('["300","400","500","700"]')
  })

  it('omits weight for variable fonts', () => {
    const content = buildFontContent('Inter')
    expect(content).not.toContain('weight:')
  })

  it('exports font as default', () => {
    const content = buildFontContent('Inter')
    expect(content).toContain('export default font')
  })

  it('includes the auto-generated header comment', () => {
    const content = buildFontContent('Inter')
    expect(content).toContain('auto-generated by scripts/generate-font.ts')
  })

  it('includes the SPDX license header', () => {
    const content = buildFontContent('Inter')
    expect(content).toContain('SPDX-License-Identifier: AGPL-3.0-or-later')
  })

  it('correctly handles underscore font names (Space_Grotesk)', () => {
    const content = buildFontContent('Space_Grotesk')
    expect(content).toContain("import { Space_Grotesk } from 'next/font/google'")
    expect(content).toContain('Space_Grotesk({')
    expect(content).not.toContain('weight:')
  })

  it('Bebas_Neue includes weight 400', () => {
    const content = buildFontContent('Bebas_Neue')
    expect(content).toContain('weight:')
    expect(content).toContain('"400"')
  })

  it('generates a const named font', () => {
    const content = buildFontContent('Outfit')
    expect(content).toContain('const font = Outfit(')
  })
})
