// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai

import type { Metadata, Viewport } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/layout/ThemeProvider'
import font from '@/lib/_font'
import { resolveConfig } from '@/lib/config'
import { deriveMainDomain } from '@/lib/seo'
import { getThemeTokens } from '@/lib/themes'
import config from '../../links.config'

// _font.ts is generated by scripts/generate-font.ts (runs as prebuild).
// It contains a single next/font/google call for the configured font — downloaded
// at build time, self-hosted, zero Google CDN at runtime.

const resolved = resolveConfig(config)
const { profile, seo, appearance } = resolved
const themeTokens = getThemeTokens(appearance.theme)
const accentColor = appearance.accentColor ?? themeTokens['--accent'] ?? '#7c3aed'
const canonicalUrl = seo?.canonicalUrl ?? 'http://localhost:3000'
const title = seo?.title ?? `${profile.name} - Links`
const description = seo?.description ?? profile.bio ?? `${profile.name}'s personal link page`
const ogImage = seo?.ogImage ?? null

const mainSiteUrl = seo?.mainSiteUrl ?? deriveMainDomain(canonicalUrl) ?? canonicalUrl
const faviconUrl = profile.avatar?.startsWith('http') ? profile.avatar : null
const avatarOrigin = (() => {
  try {
    return profile.avatar?.startsWith('http') ? new URL(profile.avatar).origin : null
  } catch {
    return null
  }
})()

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  name: title,
  description,
  url: canonicalUrl,
  dateModified: new Date().toISOString(),
  mainEntity: {
    '@type': 'Person',
    name: profile.name,
    alternateName: `@${profile.username}`,
    description,
    url: mainSiteUrl,
    mainEntityOfPage: { '@type': 'WebPage', '@id': canonicalUrl },
    ...(profile.avatar ? { image: { '@type': 'ImageObject', url: profile.avatar } } : {}),
    sameAs: (config.socials ?? []).filter((s) => s.url.startsWith('http')).map((s) => s.url),
  },
}

export const viewport: Viewport = {
  themeColor: accentColor,
  colorScheme: 'dark',
  width: 'device-width',
  initialScale: 1,
}

export const metadata: Metadata = {
  metadataBase: new URL(canonicalUrl),
  title,
  description,
  keywords: seo?.keywords,
  authors: [{ name: profile.name }],
  creator: profile.name,
  publisher: profile.name,
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
  },
  alternates: { canonical: '/' },
  icons: {
    icon: faviconUrl
      ? [
          { url: faviconUrl, sizes: 'any' },
          { url: '/icon.webp', sizes: '32x32', type: 'image/webp' },
        ]
      : [
          { url: '/favicon.ico', sizes: 'any' },
          { url: '/icon.webp', sizes: '32x32', type: 'image/webp' },
        ],
    apple: [{ url: faviconUrl ?? '/apple-touch-icon.webp', sizes: '180x180', type: 'image/webp' }],
    shortcut: faviconUrl ?? '/favicon.ico',
  },
  openGraph: {
    type: 'profile',
    locale: seo?.locale ?? 'en_US',
    url: '/',
    title,
    description,
    siteName: title,
    ...(ogImage ? { images: [{ url: ogImage, width: 1200, height: 630, alt: title }] } : {}),
  },
  twitter: {
    card: 'summary_large_image',
    title,
    description,
    creator: seo?.twitterHandle,
    ...(ogImage ? { images: [{ url: ogImage, alt: title }] } : {}),
  },
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const cssVars = (
    appearance.accentColor
      ? {
          '--accent': appearance.accentColor,
          '--beam-color': appearance.accentColor,
          '--particle-color': appearance.accentColor,
        }
      : themeTokens
  ) as React.CSSProperties

  return (
    <html
      lang={seo?.locale?.split('_')[0] ?? 'en'}
      className={font.variable}
      suppressHydrationWarning
    >
      <head>
        <link rel="preconnect" href="https://icons.germondai.com" />
        <link rel="dns-prefetch" href="https://icons.germondai.com" />
        {avatarOrigin && <link rel="preconnect" href={avatarOrigin} crossOrigin="anonymous" />}
        {avatarOrigin && <link rel="dns-prefetch" href={avatarOrigin} />}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body style={cssVars} className="min-h-dvh antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
