// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai

// Converts the OG image generated by opengraph-image.tsx to WebP and saves it
// to public/og.webp after every build - inspectable locally, usable as a static fallback.

import { readFileSync } from 'node:fs'
import sharp from 'sharp'

const src = '.next/server/app/opengraph-image.body'
const dst = 'public/og.webp'

try {
  const buf = readFileSync(src)
  await sharp(buf).webp({ quality: 85 }).toFile(dst)
  const { size } = await import('node:fs').then((m) => m.promises.stat(dst))
  console.log(`\n🖼  OG image → ${dst}  (${Math.round(size / 1024)}KB)\n`)
} catch (e) {
  if (e instanceof Error) console.warn(`⚠️  Could not extract OG image: ${e.message}`)
}
