// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai

// prebuild: writes src/lib/_font.ts with a single next/font/google call for the
// configured font so Turbopack can statically analyse it at build time.

import type { FontName } from '../src/types/config'

// non-variable fonts need an explicit weight array
export const WEIGHTS: Partial<Record<FontName, string[]>> = {
  Roboto: ['300', '400', '500', '700'],
  Poppins: ['400', '500', '600', '700'],
  Lato: ['300', '400', '700'],
  Barlow: ['300', '400', '500', '600', '700'],
  IBM_Plex_Mono: ['300', '400', '500', '700'],
  Bebas_Neue: ['400'],
  Anton: ['400'],
  DM_Serif_Display: ['400'],
}

export const buildFontContent = (name: FontName): string => {
  const ws = WEIGHTS[name]
  const wLine = ws ? `, weight: ${JSON.stringify(ws)}` : ''
  return `\
// auto-generated by scripts/generate-font.ts - do not edit manually
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai
//
// next/font/google downloads this font at build time, self-hosts it under
// /_next/static/media/, and generates @font-face with font-display: swap plus
// fallback metric overrides (ascent-override / descent-override / size-adjust)
// to prevent CLS - same technique as fontaine / @nuxt/fonts.

import { ${name} } from 'next/font/google'

const font = ${name}({ subsets: ['latin'], variable: '--font-base'${wLine} })
export default font
`
}

// only runs when executed directly, not when imported by tests
if (import.meta.main) {
  const { writeFileSync } = await import('fs')
  const { default: config } = await import('../links.config')
  const name = (config.appearance?.font ?? 'Inter') as FontName
  writeFileSync('src/lib/_font.ts', buildFontContent(name))
  console.log(`  ✓ src/lib/_font.ts  (${name})`)
}
